---
- hosts: all
  connection: paramiko
  become: yes

  vars:
    nso_install_location: "/home/{{ ansible_ssh_user }}/nso-install"
    nso_version: "5.1.0.1"
    # for example for nso-5.1.0.1.linux.x86_64.installer nso_version is "5.1.0.1"
    user: vagrant
    hostname: ntc

  tasks:
    - import_tasks: tasks/linux_packs.yml
    - import_tasks: tasks/install_nso.yml