---

    - name: Create nso install Directory
      become_user: "{{ user }}"
      file: path=/home/{{ user }}/nso-install state=directory owner={{ user }} group={{ user }}

    - name: Copy nso Installer
      become_user: "{{ user }}"
      copy: src=./files/nso-{{ nso_version }}.linux.x86_64.installer.bin dest=/home/{{ user }} owner={{ user }} group={{ user }}

    - import_tasks: tasks/install_nso.yml
      when: install_type == "local_install"
